name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # just self-hosted, no brackets

    steps:
      - run: echo "Hello from BlackHero!"
      - run: whoami
      - run: hostname
